# fly.toml app configuration file generated for cv-generator-purple-morning-5329 on 2025-01-31T14:04:08-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'cv-generator-purple-morning-5329'
primary_region = 'bog'

[build]

[env]
  KINDE_CLIENT_ID = '63cb8afa44e44c868c140d0e6523af0b'
  KINDE_CLIENT_SECRET = 'ConMe89BZ6VULXjTw79Qup609QxQCLvFgctiidFX24Ax7xg8ZcP2'
  KINDE_DOMAIN = 'https://ricardober93.kinde.com'
  KINDE_ISSUER_URL = 'https://ricardober93.kinde.com'
  KINDE_LOGOUT_REDIRECT_URI = 'https://cv-generator.fly.dev/'
  KINDE_REDIRECT_URI = 'https://cv-generator.fly.dev/api/callback'
  KINDE_SITE_URL = 'https://cv-generator.fly.dev'
  POSTGRES_URL = 'postgresql://neondb_owner:npg_wodaqA4gD5VH@ep-blue-snowflake-a8am9jph-pooler.eastus2.azure.neon.tech/neondb?sslmode=require'

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
