# fly.toml app configuration file generated for cv-generator-uz0g0a on 2025-01-31T18:21:26Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'cv-generator-uz0g0a'
primary_region = 'bog'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
